- name: Web Servers
  hosts: webservers
  become: yes

  tasks:
  - name: Install Nginx 
    apt:
      name: nginx
      state: present
  
  - name: Add hostname to index.html
    shell: echo "<h1>$(hostname)</h1>" > /var/www/html/index.nginx-debian.html

- name: Control Node
  hosts: localhost
  become: yes
  
  tasks:
  - name: Install Nginx 
    apt:
      name: nginx
      state: present

  - name: Copy NGINX Loadbalancer config
    ansible.builtin.copy:
      src: ../nginx/nginx.config
      dest: /etc/nginx/sites-available/default

  - name: Restart NGINX
    service: name=nginx state=restarted 